#!/bin/bash

set -e
brightness_file="/sys/class/backlight/intel_backlight/brightness"
current_brightness=$(cat "$brightness_file")
new_brightness="$current_brightness"

if [ "$1" = "-inc" ]
then
    new_brightness=$(( current_brightness + $2 ))
fi

if [ "$1" = "-dec" ]
then
    new_brightness=$(( current_brightness - $2 ))
fi

echo "$new_brightness" | tee "$brightness_file"

